name    'phononet-users'
version '0.0.1'
source 'http://repo.phononet.local/hg/admin/puppet-modules/phononet-users'
author 'Siegfried Wanke'
license 'Apache License, Version 2.0'
summary 'This module manage the linux user'
description 'This module create and delete linux user'
