#This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'

if ENV['PUPPET_FUTURE_PARSER'] == 'true'
    require 'puppet-syntax/tasks/puppet-syntax'
      PuppetSyntax.future_parser = true
end

if Puppet.version.to_f >= 4.5
  RSpec.configure do |c|
    c.before :each do
      Puppet.settings[:strict] = :error
    end
  end
end


# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError
end
