---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  debian-9-x64:
    roles:
      - agent
    platform: debian-9-amd64
    box_url: http://images.phononet.local/vagrant/stretch64/
    box: stretch64
    hypervisor: vagrant
CONFIG:
  type: foss
...
# vim: syntax=yaml
